### DISCUSSION TITLE
"Failed to fetch plugin config" & "Plugin not found"

### DISCUSSION THREAD

**Discussion by shadreamer** [LAION-AI/Open-Assistant#3401] [Q&A]
Good Day All, 

Setting up the LAION-AI on Linux Mint 21.1 / Python3. Web page is up on port 3000, the only issue is the inference-server is not starting. Here is my docker-compose.yaml for that section. 
```
inference-server:
    build:
      dockerfile: docker/inference/Dockerfile.server
      context: .
      target: dev
    image: oasst-inference-server:dev
    environment:
      PORT: 8000
      REDIS_HOST: inference-redis
      POSTGRES_HOST: inference-db
      POSTGRES_DB: oasst_inference
      DEBUG_API_KEYS: "0000"
      TRUSTED_CLIENT_KEYS: "6969"
      ALLOW_DEBUG_AUTH: "True"
      API_ROOT: "http://localhost:8000"
    volumes:
      - "./oasst-shared:/opt/inference/lib/oasst-shared"
      - "./inference/server:/opt/inference/server"
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      inference-redis:
        condition: service_healthy
      inference-db:
        condition: service_healthy
    profiles: ["inference"]
	
```
I also see these errors on the terminal: 

```
open-assistant-inference-server-1     | 2023-06-12 00:04:31.465 | WARNING  | oasst_inference_server.routes.configs:get_builtin_plugins:149 - Failed to fetch plugin config from http://localhost:8000/plugins/gale_pleaser: Plugin not found
open-assistant-inference-server-1     | 2023-06-12 00:04:31.470 | WARNING  | oasst_inference_server.routes.configs:get_builtin_plugins:149 - Failed to fetch plugin config from http://localhost:8000/plugins/gale_roaster: Plugin not found
open-assistant-inference-server-1     | 2023-06-12 00:04:31.475 | WARNING  | oasst_inference_server.routes.configs:get_builtin_plugins:149 - Failed to fetch plugin config from http://localhost:8000/plugins/web_retriever: Plugin not found
```

Tested each of the plugin URL and got "localhost refused to connect" prompts. (ufw firewall is inactive)

Suspecting a port conflict, I changed the port from 8000 to 8011 in the YAML. Now the pages render a little text when tested, but the plugins are still not seen or loaded by the system. 

I believe that this is the last hurdle to getting it working. How can I find / fix the block that keeps me from loading these plugins?

Thanks for any assistance.
