### ISSUE TITLE
The development docker compose configuration breaks on Mac M1

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#134]
Some of the services that get spun up fail to work due to platform incompatibility issues.  Not sure what the fix will be but this should be investigated for any Mac users.

**Comment by martinnormark** [comment]
Adding a little more info here.

It seems the culprit that has broken support for running on M1 is the `tianon/true` introduced in #119. It worked fine for me a few days back but now `docker compose up frontend-dev --build` gives me an error:

```
backend The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

I tried adding `platform: linux/arm64/v8` to the `tianon/true` images, but gets the following error back:

```
Error response from daemon: image with reference tianon/true was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd64
```

I presume it means no `arm64` support from the image?

I applied a workaround that might be feasible, using [`--profile` flag](https://docs.docker.com/compose/profiles/) instead.

It comes with the drawback that `docker compose up` will only start services that targets no profile. So to spin up all services, we'll need a "default" profile and run e.g. `docker compose --profile end2end up` and configure all services for the `end2end` profile.

The following `docker-compose` file will work:

```yaml
version: "3.7"

services:
  # This DB is for the FastAPI Backend.
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
    profiles:
      - backend-dev
      - frontend-dev
      - end2end

  # This DB is for Web Authentication and data caching.
  webdb:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oasst_web
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
    profiles:
      - frontend-dev
      - end2end

  # This lets you manually inspect the web and backend databases.
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
    profiles:
      - backend-dev
      - frontend-dev
      - end2end

  # This fakes an SMTP email server used by website authentication.
  # User registration emails can be found by going to localhost:1080 and
  # opening the emails listed.
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    profiles:
      - frontend-dev
      - end2end

  # The oassist backend service.
  backend:
    build:
      dockerfile: docker/Dockerfile.backend
    image: oasst-backend
    environment:
      - POSTGRES_HOST=db
      - DEBUG_SKIP_API_KEY_CHECK=True
      - MAX_WORKERS=1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    profiles:
      - frontend-dev
      - end2end

  # The oassist web service.
  web:
    build:
      dockerfile: docker/Dockerfile.website
    image: oasst-web
    environment:
      - DATABASE_URL=postgres://postgres:postgres@webdb/oasst_web
      - FASTAPI_URL=http://backend:8080
      - FASTAPI_KEY=1234
      - NEXTAUTH_SECRET=O/M2uIbGj+lDD2oyNa8ax4jEOJqCPJzO53UbWShmq98=
      - EMAIL_SERVER_HOST=maildev
      - EMAIL_SERVER_PORT=1025
      - EMAIL_FROM=info@example.com
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      webdb:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: bash wait-for-postgres.sh node server.js
    profiles:
      - end2end
```
