### ISSUE TITLE
Multi-GPU RL training

### ISSUE THREAD

**Issue by ghtaro** [LAION-AI/Open-Assistant#2140]
Hi,

I succeeded in running SFT and RM training in multi-gpu environment.

With the two learnt models, I tried to run RL training again in multi-gpu setup:

- 4 gpu (g5.x12large)
- CUDA11.7
- python3.8.10

and with the following script.

```
deepspeed --include=localhost:0,1,2,3 --master_port 61000 trainer_rl.py \
--configs defaults_rlhf \
--rank_model $REWARD_MODEL \
--sft_model $SFT_MODEL
```

I modified config_rl.yaml below:

```
defaults_rlhf:
  dataset:
  eval_size: 4
  rank_model: TODO
  sft_model: TODO
  eval_prompts:
  batch_size: 64
  epochs: 10
  datasets:
    - webgpt:
        val_split: 0.0
        fraction: 1
  cache_dir: .cache
  quantization: false
  seq2seqmodel: false
  output_dir: output
  reward_model_batch_size: 32

debug_rlhf:
  rank_model: /local/home/sanagnos/general/Open-Assistant/model/reward/instructor/facebook/galactica-125m-finetuned/checkpoint-500/
  sft_model: /local/home/sanagnos/general/Open-Assistant/model/model_training/EleutherAI/pythia-70m-deduped-base-finetuned/checkpoint-20/
  batch_size: 2
```

also modified ppo_config.yaml just to add wandb tracker

```
train:
  seq_length: 1024
  epochs: 100
  total_steps: 10000
  batch_size: 1

  checkpoint_interval: 10000
  eval_interval: 100

  pipeline: "PromptPipeline"
  trainer: "AcceleratePPOTrainer"

  tracker: "wandb"

model:
  model_path: "lvwerra/gpt2-imdb"
  num_layers_unfrozen: 2

tokenizer:
  tokenizer_path: "gpt2"
  truncation_side: "right"

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 10000 # train.total_steps
    eta_min: 1.0e-4

method:
  name: "ppoconfig"
  num_rollouts: 16
  chunk_size: 16
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 40
    top_k: 0
    top_p: 1.0
    do_sample: True
```

Then, I have got the following error message. It looks like eval_prompts are not properly generated and failed miserably in evaluation...

```
[rollout 16 / 16]:   0%|          | 0/16 [00:20<?, ?it/s]
[rollout 16 / 16]: 100%|██████████| 16/16 [00:20<00:00,  1.27s/it]
[rollout 16 / 16]: 100%|██████████| 16/16 [00:20<00:00,  1.27s/it]
[RANK 0] Starting training
[RANK 0] Evaluating model

[generation sweep 0/1 | eval batch 0/1]:   0%|          | 0/1 [00:00<?, ?it/s]
[generation sweep 1/1 | eval batch 1/1]:   0%|          | 0/1 [00:00<?, ?it/s]
[generation sweep 1/1 | eval batch 1/1]: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
[generation sweep 1/1 | eval batch 1/1]: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
[RANK 0] Computing rewards
Traceback (most recent call last):
  File "trainer_rl.py", line 95, in <module>
    trainer = trlx.train(
  File "/databricks/conda/envs/pytorch/lib/python3.8/site-packages/trlx/trlx.py", line 119, in train
    trainer.learn()
  File "/databricks/conda/envs/pytorch/lib/python3.8/site-packages/trlx/trainer/accelerate_base_trainer.py", line 455, in learn
    results = self.evaluate()
  File "/databricks/conda/envs/pytorch/lib/python3.8/site-packages/trlx/trainer/accelerate_base_trainer.py", line 357, in evaluate
    self.reward_fn(
  File "/databricks/conda/envs/pytorch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "trainer_rl.py", line 69, in rank_model_fn
    inputs = rank_tokenizer(samples, return_tensors="pt", padding=True)
  File "/databricks/conda/envs/pytorch/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2523, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/databricks/conda/envs/pytorch/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2609, in _call_one
    return self.batch_encode_plus(
  File "/databricks/conda/envs/pytorch/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2800, in batch_encode_plus
    return self._batch_encode_plus(
  File "/databricks/conda/envs/pytorch/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 462, in _batch_encode_plus
    for key in tokens_and_encodings[0][0].keys():
IndexError: list index out of range
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /dbfs/FileStore/tables/JDD/user/imoto/chatgpt2/model/model_training/trainer_ │
│ rl.py:95 in <module>                                                         │
│                                                                              │
│    92 │   trlx_config.model.model_path = training_conf.sft_model             │
│    93 │   trlx_config.train.batch_size = training_conf.batch_size            │
│    94 │                                                                      │
│ ❱  95 │   trainer = trlx.train(                                              │
│    96 │   │   training_conf.sft_model,                                       │
│    97 │   │   reward_fn=rank_model_fn,                                       │
│    98 │   │   prompts=prompts,                                               │
│                                                                              │
│ /databricks/conda/envs/pytorch/lib/python3.8/site-packages/trlx/trlx.py:119  │
│ in train                                                                     │
│                                                                              │
│   116 │   eval_pipeline = get_pipeline(config.train.pipeline)(eval_prompts,  │
│   117 │   trainer.add_eval_pipeline(eval_pipeline)                           │
│   118 │                                                                      │
│ ❱ 119 │   trainer.learn()                                                    │
│   120 │   return trainer                                                     │
│   121                                                                        │
│                                                                              │
│ /databricks/conda/envs/pytorch/lib/python3.8/site-packages/trlx/trainer/acce │
│ lerate_base_trainer.py:455 in learn                                          │
│                                                                              │
│   452 │   │   │   │   │   │   state = json.load(f)                           │
│   453 │   │   │   │   │   │   self.iter_count = state["iter_count"]          │
│   454 │   │   else:                                                          │
│ ❱ 455 │   │   │   results = self.evaluate()                                  │
│   456 │   │   │   self.accelerator.log(results, step=self.iter_count)        │
│   457 │   │                                                                  │
│   458 │   │   tbar = logging.tqdm(                                           │
│                                                                              │
│ /databricks/conda/envs/pytorch/lib/python3.8/site-packages/trlx/trainer/acce │
│ lerate_base_trainer.py:357 in evaluate                                       │
│                                                                              │
│   354 │   │   │   │   if self.reward_fn:                                     │
│   355 │   │   │   │   │   logger.info("Computing rewards")                   │
│   356 │   │   │   │   │   rewards = torch.tensor(                            │
│ ❱ 357 │   │   │   │   │   │   self.reward_fn(                                │
│   358 │   │   │   │   │   │   │   samples=str_samples,                       │
│   359 │   │   │   │   │   │   │   prompts=str_prompts,                       │
│   360 │   │   │   │   │   │   │   outputs=str_outputs,                       │
│                                                                              │
│ /databricks/conda/envs/pytorch/lib/python3.8/site-packages/torch/autograd/gr │
│ ad_mode.py:27 in decorate_context                                            │
│                                                                              │
│    24 │   │   @functools.wraps(func)                                         │
│    25 │   │   def decorate_context(*args, **kwargs):                         │
│    26 │   │   │   with self.clone():                                         │
│ ❱  27 │   │   │   │   return func(*args, **kwargs)                           │
│    28 │   │   return cast(F, decorate_context)                               │
│    29 │                                                                      │
│    30 │   def _wrap_generator(self, func):                                   │
│                                                                              │
│ /dbfs/FileStore/tables/JDD/user/imoto/chatgpt2/model/model_training/trainer_ │
│ rl.py:69 in rank_model_fn                                                    │
│                                                                              │
│    66 │   # TODO sync with reward modelling team on how to do this more tran │
│    67 │   @torch.no_grad()                                                   │
│    68 │   def rank_model_fn(samples, **kwargs):                              │
│ ❱  69 │   │   inputs = rank_tokenizer(samples, return_tensors="pt", padding= │
│    70 │   │   del inputs["token_type_ids"]                                   │
│    71 │   │   return rank_model(**inputs).logits[:, 0].detach().cpu()        │
│    72                                                                        │
│                                                                              │
│ /databricks/conda/envs/pytorch/lib/python3.8/site-packages/transformers/toke │
│ nization_utils_base.py:2523 in __call__                                      │
│                                                                              │
│   2520 │   │   │   # input mode in this case.                                │
│   2521 │   │   │   if not self._in_target_context_manager:                   │
│   2522 │   │   │   │   self._switch_to_input_mode()                          │
│ ❱ 2523 │   │   │   encodings = self._call_one(text=text, text_pair=text_pair │
│   2524 │   │   if text_target is not None:                                   │
│   2525 │   │   │   self._switch_to_target_mode()                             │
│   2526 │   │   │   target_encodings = self._call_one(text=text_target, text_ │
│                                                                              │
│ /databricks/conda/envs/pytorch/lib/python3.8/site-packages/transformers/toke │
│ nization_utils_base.py:2609 in _call_one                                     │
│                                                                              │
│   2606 │   │   │   │   │   f" {len(text_pair)}."                             │
│   2607 │   │   │   │   )                                                     │
│   2608 │   │   │   batch_text_or_text_pairs = list(zip(text, text_pair)) if  │
│ ❱ 2609 │   │   │   return self.batch_encode_plus(                            │
│   2610 │   │   │   │   batch_text_or_text_pairs=batch_text_or_text_pairs,    │
│   2611 │   │   │   │   add_special_tokens=add_special_tokens,                │
│   2612 │   │   │   │   padding=padding,                                      │
│                                                                              │
│ /databricks/conda/envs/pytorch/lib/python3.8/site-packages/transformers/toke │
│ nization_utils_base.py:2800 in batch_encode_plus                             │
│                                                                              │
│   2797 │   │   │   **kwargs,                                                 │
│   2798 │   │   )                                                             │
│   2799 │   │                                                                 │
│ ❱ 2800 │   │   return self._batch_encode_plus(                               │
│   2801 │   │   │   batch_text_or_text_pairs=batch_text_or_text_pairs,        │
│   2802 │   │   │   add_special_tokens=add_special_tokens,                    │
│   2803 │   │   │   padding_strategy=padding_strategy,                        │
│                                                                              │
│ /databricks/conda/envs/pytorch/lib/python3.8/site-packages/transformers/toke │
│ nization_utils_fast.py:462 in _batch_encode_plus                             │
│                                                                              │
│   459 │   │   # To match each overflowing sample with the original sample in │
│   460 │   │   # we add an overflow_to_sample_mapping array (see below)       │
│   461 │   │   sanitized_tokens = {}                                          │
│ ❱ 462 │   │   for key in tokens_and_encodings[0][0].keys():                  │
│   463 │   │   │   stack = [e for item, _ in tokens_and_encodings for e in it │
│   464 │   │   │   sanitized_tokens[key] = stack                              │
│   465 │   │   sanitized_encodings = [e for _, item in tokens_and_encodings f │
╰──────────────────────────────────────────────────────────────────────────────╯
IndexError: list index out of range
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
```

BTW, I was able to run the RL training with single-gpu.

```
python trainer_rl.py \
--configs defaults_rlhf \
--rank_model $REWARD_MODEL \
--sft_model $SFT_MODEL
```

I am stuck for a couple of days already... It would be very helpful if you tell me any advice to sort it out.
