### ISSUE TITLE
what is the process to train llama-30b-sft-7 model ?

### ISSUE THREAD

**Issue by premanand09** [LAION-AI/Open-Assistant#3286]
what is the process to train llama-30b-sft-7 model ? Should I directly train llama model with llama-30b-sft-7 config ? or do i have to train  llama on pretrain config first ? what is the process ?

**Comment by andreaskoepf** [comment]
If you have LLaMA weights you find a xored version of SFT-7 here: [OpenAssistant/oasst-sft-7-llama-30b-xor](https://huggingface.co/OpenAssistant/oasst-sft-7-llama-30b-xor). If you search for "OpenAssistant/oasst-sft-7-llama-30b" on the HuggingFace hub you probably will even find uploads of the conversion process.

The training was done in a two-stage process, first "pre-training" and then fine tuning. More recent papers show that this might not be ideal/necessary (see Lima or QLoRA).

Configuration for the 2nd stage SFT-7 was:
```
llama-30b-sft-7:
  dtype: fp16
  log_dir: "llama_log_30b"
  learning_rate: 1e-5
  model_name: /home/ubuntu/Open-Assistant/model/model_training/.saved/llama-30b-super-pretrain/checkpoint-3500
  #model_name: OpenAssistant/llama-30b-super-pretrain
  output_dir: llama_model_30b
  deepspeed_config: configs/zero3_config_sft.json
  weight_decay: 0.0
  residual_dropout: 0.0
  max_length: 2048
  use_flash_attention: true
  warmup_steps: 20
  gradient_checkpointing: true
  gradient_accumulation_steps: 12
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 3
  eval_steps: 101
  save_steps: 485
  num_train_epochs: 4
  save_total_limit: 3
  use_custom_sampler: true
  sort_by_length: false
  #save_strategy: steps
  save_strategy: epoch
  datasets:
    - oasst_export:
        lang: "bg,ca,cs,da,de,en,es,fr,hr,hu,it,nl,pl,pt,ro,ru,sl,sr,sv,uk"
        input_file_path: 2023-04-12_oasst_release_ready_synth.jsonl.gz
        val_split: 0.05
    - vicuna:
        val_split: 0.05
        max_val_set: 800
        fraction: 1.0
    - dolly15k:
        val_split: 0.05
        max_val_set: 300
    - grade_school_math_instructions:
        val_split: 0.05
    - code_alpaca:
        val_split: 0.05
        max_val_set: 250
# Dataset Mix:
# oasst_export: 100.00% (37605)
# vicuna: 100.00% (55744)
# dolly15k: 100.00% (14264)
# grade_school_math_instructions: 100.00% (8352)
# code_alpaca: 100.00% (19020)
```
