### ISSUE TITLE
The dev instance website doesn't function

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#372]
When trying to login via email, no email is sent.  This is likely due to a variety of environment variables not being set.

To do this, I propose the following:
- [] Store all the needed secrets in Github repo secrets (an admin will need to do this)
- [] Update the deployment workflow to set each environment variable according to the secret with a line like
      ```
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
```
- [] Update the ansible build to reference all the required secrets.

The secrets we need to be setting right are:
- `DATABASE_URL`
- `DISCORD_CLIENT_ID`
- `DISCORD_CLIENT_SECRET`
- `EMAIL_SERVER_HOST`
- `EMAIL_SERVER_PASSWORD`
- `EMAIL_SERVER_PORT`
- `EMAIL_SERVER_USER`
- `EMAIL_FROM`
- `FASTAPI_KEY`
- `NEXTAUTH_SECRET`

Other environment variables we need to set are:
- `NEXTAUTH_URL`
- `FASTAPI_URL`
